baseURL = 'https://electrobot.fr/'
languageCode = 'fr-fr'
defaultContentLanguage = 'fr'
title = 'Electrobot'
theme = 'hugo-book'

[params]
  BookLogo = 'logo.png'

[caches]
  [caches.images]
    dir = ':cacheDir/images'
